name: Testing workflow

on: push

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Install and run clang-format
      - name: "Install clang-format"
        run: sudo apt install clang-format
      - name: "Run clang-format"
        run: clang-format --dry-run -Werror src/* tests/*.cpp


  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install dependencies"
        run: sudo apt install libeigen3-dev libboost-all-dev libyaml-cpp-dev
      - name: "Compile and build code"
        run: |
          mkdir build
          cp tests/testconfig.yml build/
          cd build/
          cmake ..
          make -j
      - name: "Save build folder"
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/
          retention-days: 1


  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install dependencies"
        run: sudo apt install libeigen3-dev libboost-all-dev libyaml-cpp-dev
      - name: "Compile and build code"
        run: |
          mkdir build
          cp tests/testconfig.yml build/
          cd build/
          cmake ..
          make -j
      - name: "Save build folder"
        uses: actions/upload-artifact@v2
        with:
          name: build2
          path: build/
          retention-days: 1
    # needs: build
    # runs-on: ubuntu-latest
    # steps:
    #   - uses: actions/checkout@v2
    #   - name: "Download build folder"
    #       uses: actions/download-artifact@v2
    #         with:
    #           name: build
    #     - name: "Test code"
    #       run: |
    #         cd build/
    #         make test
